### ISSUE TITLE
Azimuth Compression is a chirp

### ISSUE THREAD

**Issue by jks7592** [jmfriedt/sentinel1_level0#4]
I took a grad SAR course, and I've forked a fellow former student's RITSAR package to update it to python3. I hope to use some of your code to wrap with python so I can mess around with space based SAR as I currently only have toy airborn data. I'm a novice python fan, so it's going to take me a few months at least just to figure out the parallelization you talked about at the end. 

Anyway, azimuth is sometimes called the "doppler" direction because there's a doppler shift as your relative position to the scene center changes. Note, that's also assuming an airborn platform in level flight, I've heard rumors that for space you gotta account for a whole list of satellite motion phenomena.

**Comment by mohamed-aamir** [comment]
For my project, I recently learned about SAR data and sentinel. Then I discovered that SNAP is unable to open RAW files. Then I looked for software that could open RAW files. I arrived here and saw that the source code is written in C. I decided to learn Python so that I could develop open source software in it, but seeing you have the same interest as me is exciting. I'd like to know if you have any new information on your mission's progress.

**Comment by jks7592** [comment]
So I finally got the code from this repository working and got it to decompress a single image... but it literally took all night to do. There's a matlab script for the next steps but I don't have matlab, so I tried moving the reading script for these output files into python and never finished. It seems like the C code isn't terribly complex, and I think there's a way to decompress with python and struct.unpack, but I remember last time I tried using that it took me a week to figure out how to read the first bit of a header and would take far more time than I have available. I was surprised there isn't something out there that at least efficiently does the decompression... then I found out the compression format is a custom Airbus version of a standard compression method that's just special enough to make it non-compatible.

**Comment by jmfriedt** [comment]
All Matlab-language scripts are executed with GNU/Octave (https://www.gnu.org/software/octave/index). The C code is not written for efficiency but readability and ease of debugging, although 1 night to process a dataset sounds long, depending though on hard disk access speed since most time will be spent accessing files. On my SSD-based mass storage medium, decoding a raw dataset takes about an hour. You might want to try and create a ramdisk,
``tmpfs /tmp tmpfs   nodev,nosuid,size=9612M  0  0`` in ``/etc/fstab``, and process a file from there to assess if disk access bandwidth is your limiting factor.
