### ISSUE TITLE
Part of the decoded result of strimap mode data is wrong!

### ISSUE THREAD

**Issue by WRangers** [jmfriedt/sentinel1_level0#6]
Hi, jmfriedt! Thank you for your code, from which I learned a lot. But I find a problem that part of the decoded result of strimap mode data is wrong, like the figure below. The first picture is the echo, and the second one is the result of pulse compression. It's obvious that there are some issues with the right half raw data. I don't know how to solve it. So I am asking for your help! Thank you!
![e35a263f7ee61adde0eb634006379b9](https://user-images.githubusercontent.com/50192406/161421717-8b6fa0bc-dea4-4648-afa3-db3bed082928.png)
![ba234ede08e642ecceb181cd6b1fc2f](https://user-images.githubusercontent.com/50192406/161421756-cb9ecfec-2d03-4f01-b298-0e08db33627e.png)

**Comment by WRangers** [comment]
I also try modes of strimap mode, like S3, S4, S6, which have the same problem.

**Comment by jmfriedt** [comment]
That is awkward to say the least. What file are you using so I can try and debug on my side as well?

**Comment by WRangers** [comment]
The data I uesed is "[S1A_S3_RAW__0SDH_20220216T213553_20220216T213619_041943_04FEA9_6D05](https://search.asf.alaska.edu/#/?zoom=9.135&center=-46.317,-24.135&start=2021-12-31T16:00:00Z&end=2022-02-21T15:59:59Z&resultsLoaded=true&granule=S1A_S3_GRDH_1SDH_20220216T213554_20220216T213618_041943_04FEA9_3F2D-GRD_HD&view=equitorial&beamModes=S3). The collapse begins about from the 17920th rang line. Thank you for your reply!

**Comment by jmfriedt** [comment]
This appears to be a case I had not considered (since I was not aware that it was possible). When looking at the output log from 
```
read_file S1A_S3_RAW__0SDH_20220216T213553_20220216T213619_041943_04FEA9_6D05.SAFE/s1a-s3-raw-s-hh-20220216t213553-20220216t213619-041943-04fea9.dat >& log
```
we generate a 8420566000 bytes (that's 8.4 GB) output  ``resultSW02_T1329082572_NQ10919.bin`` but most interestingly we see that in the beginning of the log file we have
```
cat log | grep Swath=2 | head
        Decim=4 TXPRR=^87d2=2002        TXPSF=-0x32aa=12970 TXPL=0000067a=1658 PRI=00004c2b=19499 Polar=3 Typ=1(0) Swath=2 NQ=10919
```
but later (focus on the last parameter NQ at the end of the line)
```
cat log | grep Swath=2 | head -20000 | tail
        Decim=4 TXPRR=^87d2=2002        TXPSF=-0x32aa=12970 TXPL=0000067a=1658 PRI=00004c2b=19499 Polar=3 Typ=0(0) Swath=2 NQ=10947
```
so that it is still called Swath 2 but the parameters have changed (PRR, PRI and PSF remain so pulse compression will be valid, but NQ has changed so that the linewidth must be adapted). I think you will have to process the two parts separatly, first the NQ=10919 part and then the NQ=10947. I cannot see a way of merging two datasets with different widths. Please check the updated read_file version I just commited which now creates a new file when NQ changes, even if the swath index remains the same. In the log you should now see when processing the same dataset
```
99 Polar=3 Typ=0(0) Swath=2 NQ=10919
, finished processing 14252 echo
0c1c: 1(1)      65(65)  12(12)  0938: 3(3)      Count=10        Len=14346(61..65533)
        Time: 1329082582:16509  352ef853(352EF853)      WordIndex=1f    WordVal=3835    00004cc
a 00005c7d BAQ=0c(c) BlockLen=1f(1F)
        Decim=4 TXPRR=^87d2=2002        TXPSF=-0x32aa=12970 TXPL=0000067a=1658 PRI=00004c2b=194
99 Polar=3 Typ=0(0) Swath=2
FILE written 21894 19250
 NQ=10947
``` 
meaning that a new file with NQ=10947 is created and you should get two different files ``resultSW02_T1329082572_NQ10919.bin`` (3363052000 bytes large) and ``resultSW02_T1329082582_NQ10947.bin`` that can be processed independently, providing the appropriate argument to NQ.
Good luck, let me know how if that solves the problem.

**Comment by WRangers** [comment]
I see! In fact, I wrote a modified version of the original code, which can save the parameters in a `.csv` file. Now I add the `NQ` parameter to the output '.csv' file and extract the data of each range line according to its `NQ` value. However, it's noticeable that the `sampling_win_start time` and the `sample_win_len` are also changed. So, for the value of pulse compression data, its range direction length should be the greater one in `2*10947` and `2*10919`. And those two kinds of range line should be aligned to the `sampling win start time`.

![image](https://user-images.githubusercontent.com/50192406/161431149-977dfd49-0651-4771-869b-b11ef8b4c6af.png)

Thanks a million! Best wished!
